### ISSUE TITLE
更更新了Python，发现vim挂了

### ISSUE THREAD

**Issue by bg4hkq** [Fechin/oh-my-vim#1]
mac系统，用brew更新了一下，查了一下vim和python都更新了，也不知道是哪个的问题。
你哪里有这种情况么？
我已经把.vim删了，重新git下来装一次试试。

**Comment by bg4hkq** [comment]
重新git，然后setup了一遍。发现是这样的。
`Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command:  NERDTree | endif
Press ENTER or type command to continue`

**Comment by Fechin** [comment]
http://stackoverflow.com/questions/25990126/nerdtree-autocmd-error-vim
